set_property IOSTANDARD LVCMOS33 [get_ports {q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {q[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W14 [get_ports {q[0]}]
set_property PACKAGE_PIN Y14 [get_ports {q[1]}]
set_property PACKAGE_PIN T11 [get_ports {q[2]}]
set_property PACKAGE_PIN D20 [get_ports rst]
set_property PACKAGE_PIN D19 [get_ports clk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports {q[3]}]
set_property PACKAGE_PIN T10 [get_ports {q[3]}]
