set_property PACKAGE_PIN N15 [get_ports C]
set_property PACKAGE_PIN M15 [get_ports S]
set_property IOSTANDARD LVCMOS33 [get_ports C]
set_property IOSTANDARD LVCMOS33 [get_ports S]
set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports B]
set_property PACKAGE_PIN D19 [get_ports A]
set_property PACKAGE_PIN D20 [get_ports B]
